version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: CONTAINER_NAME
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_DB: DB_NAME
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - NETWORK_NAME

networks:
  NETWORK_NAME:
